Microsoft/MvcMovie/MvcBank/Controllers/BankController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcBank.Data;
using MvcBank.Models;
using MvcBank.Models.ViewModels;

namespace MvcBank.Controllers
{
    public class BankController : Controller
    {
        private readonly BankDbContext _context;
        public BankController(BankDbContext context)
        {
            _context = context;
            
        }

        [HttpGet]
        public async Task<IActionResult> BankList()
        {
            var banks = await _context.Banks.ToListAsync();

            return View(banks);
        }


        [HttpGet]
        public IActionResult CreateBank()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBank(CreateBankVM viewModel)
        {
            if (ModelState.IsValid)
            {
                var bank = new Bank
                {
                    BankName = viewModel.BankName,
                };
                _context.Banks.Add(bank);
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = " Bank Successfully Created!";
                return RedirectToAction(nameof(BankList));

            }
            return View(viewModel);
        }


        [HttpGet]
        public async Task<ActionResult> EditBank(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var bank = await _context.Banks.FindAsync(id);

            if (bank == null)
            {
                return NotFound();
            }

            return View(bank);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBank(Guid id, Bank bank)
        {
            if (id != bank.BankId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(bank);
                await _context.SaveChangesAsync();
                TempData["UpdateMessage"] = " Bank Successfully Updated!";
                return RedirectToAction(nameof(BankList));
            }
            return View(bank);
        }


        [HttpGet]
        public async Task<IActionResult> DeleteBank(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var bank = await _context.Banks.FirstOrDefaultAsync(b => b.BankId == id);

            if (bank == null)
            {
                return NotFound();
            }

            TempData["BankName"] = bank.BankName;

            return View(bank);
        }


        [HttpPost]
        [ActionName("DeleteBank")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteBankConfirm(Guid id)
        {
            var bank = await _context.Banks.FindAsync(id);

            if (bank != null)
            {
                _context.Banks.Remove(bank);
            }
            await _context.SaveChangesAsync();
            TempData["DeleteMessage"] = " Bank Successfully Deleted!";
            return RedirectToAction(nameof(BankList));
        }







        [AcceptVerbs("Post", "Get")]
        public async Task<IActionResult> IsBankExists(string BankName)
        {
            var data = await _context.Banks.Where(b => b.BankName == BankName).FirstOrDefaultAsync();

            if (data != null)
            {
                //return BadRequest($"Bank {BankName} already Exists!");
                return Json($"Bank {BankName} already Exists!");
            }

            else
            {
                return Json(true);
                //return Ok(true);
            }


        }
    }
}

Microsoft/MvcMovie/MvcBank/Controllers/BranchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcBank.Data;
using MvcBank.Models;
using MvcBank.Models.ViewModels;

namespace MvcBank.Controllers
{
    public class BranchController : Controller
    {

        private readonly BankDbContext _context;
        public BranchController(BankDbContext context)
        {
            _context = context;

        }
        
        [HttpGet]
        public async Task<IActionResult> BranchList()
        {
            var branch = await _context.Branch.Include(m => m.Bank).ToListAsync();

            return View(branch);
        }

       
        [HttpGet]
        public IActionResult CreateBranch()
        {
            var viewModel = new CreateBranchVM
            {
                Banks = _context.Banks.Select(b => new SelectListItem
                {
                    Value = b.BankId.ToString(),
                    Text = b.BankName
                })
            };

            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateBranch(CreateBranchVM viewModel)
        {
            if (ModelState.IsValid)
            {
                var branch = new Branch
                {
                    BranchId = Guid.NewGuid(),
                    BranchName = viewModel.BranchName,
                    BankId = viewModel.BankId
                };
                await _context.AddAsync(branch);
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Branch successfully created!";
                return RedirectToAction(nameof(BranchList));
            }

            viewModel.Banks = _context.Banks.Select(g => new SelectListItem
            {
                Value = g.BankId.ToString(),
                Text = g.BankName
            });

            return View(viewModel);
        }


        [HttpGet]
        public async Task<IActionResult> EditBranch(Guid id)
        {
            var branch = await _context.Branch.FindAsync(id);

            if (branch == null)
            {
                return NotFound();
            }

            var viewModel = new EditBranchVM
            {
                BranchId = branch.BranchId,
                BranchName = branch.BranchName,
                BankId = branch.BankId,
                Banks = _context.Banks.Select(b => new SelectListItem
                {
                    Value = b.BankId.ToString(),
                    Text = b.BankName
                })
            };

            return View(viewModel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBranch(EditBranchVM viewModel)
        {
            if (ModelState.IsValid)
            {
                var branch = await _context.Branch.FindAsync(viewModel.BranchId);

                if (branch == null)
                {
                    return NotFound();
                }

                branch.BranchName = viewModel.BranchName;
                branch.BankId = viewModel.BankId;

                _context.Update(branch);
                await _context.SaveChangesAsync();
                TempData["UpdateMessage"] = "Branch successfully Updated!";
                return RedirectToAction(nameof(BranchList));
            }

            viewModel.Banks = _context.Banks.Select(g => new SelectListItem
            {
                Value = g.BankId.ToString(),
                Text = g.BankName
            });

            return View(viewModel);

        }


        [HttpGet]
        public async Task<IActionResult> DeleteBranch(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var branch = await _context.Branch.Include(b => b.Bank).FirstOrDefaultAsync(b =>b.BranchId == id);

            if (branch == null)
            {
                return NotFound();
            }

            TempData["BranchName"] = branch.BranchName;

            return View(branch);
        }


        [HttpPost]
        [ActionName("DeleteBranch")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteBranchConfirm(Guid id)
        {
            var branch = await _context.Branch.FindAsync(id);

            if (branch != null)
            {
                _context.Branch.Remove(branch);
            }
            await _context.SaveChangesAsync();
            TempData["DeleteMessage"] = "Branch successfully Deleted!";
            return RedirectToAction(nameof(BranchList));
        }

        [AcceptVerbs("Post", "Get")]
        public async Task<IActionResult> IsBranchExists(string BranchName)
        {
            var data = await _context.Branch.Where(b => b.BranchName == BranchName).FirstOrDefaultAsync();

            if (data != null)
            {
                return Json($"Branch {BranchName} already in Website!");
            }

            else
            {
                return Json(true);
            }


        }
    }
}

Microsoft/MvcMovie/MvcBank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bank</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcBank.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fw-bold">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcBank</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bank" asp-action="BankList">Bank</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Branch" asp-action="BranchList">Branch</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - MvcBank - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>